plugins {
	alias(libs.plugins.org.springframework.boot)
	alias(libs.plugins.io.spring.dependency.management)
	id "nebula.integtest" version "8.2.0"
	id 'java'
	id "fi.evident.beanstalk" version "0.3.3"
}

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/milestone" }
	maven { url "https://repo.spring.io/snapshot" }
}


dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

    // Database drivers
    implementation 'org.postgresql:postgresql:42.7.4'
    implementation 'com.amazonaws.secretsmanager:aws-secretsmanager-jdbc:2.0.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'

	integTestImplementation 'org.htmlunit:htmlunit'
}

tasks.withType(Test).configureEach {
	useJUnitPlatform()
	
}

// SNAPSHOT will be replaced with 'yyyyMMdd.HHmms' label
version = '0.1-SNAPSHOT'
