server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 1800000
      connection-timeout: 30000
